### ISSUE TITLE
Unable to setup Auth server for vscode-webrm

### ISSUE THREAD

**Issue by LinnZawWin** [Sheeley7/vscode-webrm-auth#4]
'Deploy to Azure' button is not working anymore. Is there any alternative way to setup Auth server for vscode-webrm?

**Comment by Sheeley7** [comment]
Hi Linn, if you cannot setup the auth server manually, there is an alternative to use local auth. the documentation hasn't been updated, but in the settings of the extension in vscode, there are 3 values "App Client ID", "App Client Secret", and "Use Local Auth". This eliminates the need for the auth server and the vscode extension will make the auth calls directly. Just be warry who you give the client secret to. 
![image](https://user-images.githubusercontent.com/5257942/117721141-7d06fa80-b1ad-11eb-9525-b3795732e457.png)

**Comment by LinnZawWin** [comment]
Thanks, it is working with "Use Local Auth". When you update the [documentation](https://github.com/Sheeley7/vscode-webrm/blob/master/README.md), please specify that `http://localhost:8350/auth` needs to be added as one of the Redirect URIs.
